apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: f7iss007o-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/f7iss007o-java-quarkus-gitops